import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import usersRouter from "./users";
import freelancersRouter from "./freelancers";
import employersRouter from "./employers";
import jobRequirementsRouter from "./jobRequirements";
import bookingsRouter from "./bookings";
import agreementsRouter from "./agreements";
import openaiChatRouter from "./openaiChat";
import dashboardRouter from "./dashboard";
import verifyDocumentsRouter from "./verifyDocuments";
import meetingsRouter from "./meetings";
import jobInterestsRouter from "./jobInterests";
import notificationsRouter from "./notifications";
import demoRouter from "./demo";
import subscriptionsRouter from "./subscriptions";
import adminRouter from "./admin";
import authTrackingRouter from "./authTracking";
import resumeParserRouter from "./resumeParser";
import reviewsRouter from "./reviews";
import savedFreelancersRouter from "./savedFreelancers";
import portfolioRouter from "./portfolio";
import milestonesRouter from "./milestones";
import analyticsRouter from "./analytics";
import publicProfileRouter from "./publicProfile";

const router: IRouter = Router();

router.use(healthRouter);
router.use(demoRouter);
router.use(storageRouter);
router.use(usersRouter);
router.use(savedFreelancersRouter);
router.use(portfolioRouter);
router.use(freelancersRouter);
router.use(employersRouter);
router.use(jobRequirementsRouter);
router.use(bookingsRouter);
router.use(agreementsRouter);
router.use(meetingsRouter);
router.use(jobInterestsRouter);
router.use(notificationsRouter);
router.use(subscriptionsRouter);
router.use(adminRouter);
router.use(authTrackingRouter);
router.use(resumeParserRouter);
router.use(reviewsRouter);
router.use(milestonesRouter);
router.use(analyticsRouter);
router.use(publicProfileRouter);
router.use(openaiChatRouter);
router.use(dashboardRouter);
router.use(verifyDocumentsRouter);

export default router;
