import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import usersRouter from "./users";
import freelancersRouter from "./freelancers";
import employersRouter from "./employers";
import jobRequirementsRouter from "./jobRequirements";
import bookingsRouter from "./bookings";
import agreementsRouter from "./agreements";
import openaiChatRouter from "./openaiChat";
import aiMatchRouter from "./aiMatch";
import aiAssistRouter from "./aiAssist";
import dashboardRouter from "./dashboard";
import documentsRouter from "./documents";
import meetingsRouter from "./meetings";
import jobInterestsRouter from "./jobInterests";
import notificationsRouter from "./notifications";
import demoRouter from "./demo";
import subscriptionsRouter from "./subscriptions";
import tokenUsageRouter from "./tokenUsage";
import adminRouter from "./admin";
import authTrackingRouter from "./authTracking";
import resumeParserRouter from "./resumeParser";
import reviewsRouter from "./reviews";
import savedFreelancersRouter from "./savedFreelancers";
import portfolioRouter from "./portfolio";
import milestonesRouter from "./milestones";
import analyticsRouter from "./analytics";
import publicProfileRouter from "./publicProfile";
import availabilityRouter from "./availability";
import accountRouter from "./account";
import teamRouter from "./team";
import cruiseModeRouter from "./cruiseMode";
import talentSearchRouter from "./talentSearch";
import conversationsRouter from "./conversations";
import employerDocumentsRouter from "./employerDocuments";
import cronRouter from "./cron";
import countriesRouter from "./countries";
import exchangeRatesRouter from "./exchangeRates";

const router: IRouter = Router();

router.use(healthRouter);
router.use(countriesRouter);
router.use(exchangeRatesRouter);
router.use(demoRouter);
router.use(storageRouter);
router.use(usersRouter);
router.use(accountRouter);
router.use(savedFreelancersRouter);
router.use(portfolioRouter);
router.use(freelancersRouter);
router.use(availabilityRouter);
router.use(employersRouter);
router.use(jobRequirementsRouter);
router.use(bookingsRouter);
router.use(agreementsRouter);
router.use(meetingsRouter);
router.use(jobInterestsRouter);
router.use(notificationsRouter);
router.use(subscriptionsRouter);
router.use(tokenUsageRouter);
router.use(adminRouter);
router.use(authTrackingRouter);
router.use(resumeParserRouter);
router.use(reviewsRouter);
router.use(milestonesRouter);
router.use(analyticsRouter);
router.use(publicProfileRouter);
router.use(openaiChatRouter);
router.use(aiMatchRouter);
router.use(aiAssistRouter);
router.use(dashboardRouter);
router.use(documentsRouter);
router.use(teamRouter);
router.use(cruiseModeRouter);
router.use(talentSearchRouter);
router.use(conversationsRouter);
router.use(employerDocumentsRouter);
router.use(cronRouter);

export default router;
