// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/talentlock-themes/IndigoSlate.tsx": () => import("../components/mockups/talentlock-themes/IndigoSlate.tsx"),
  "./components/mockups/talentlock-themes/MidnightDark.tsx": () => import("../components/mockups/talentlock-themes/MidnightDark.tsx"),
  "./components/mockups/talentlock-themes/NavyGold.tsx": () => import("../components/mockups/talentlock-themes/NavyGold.tsx")
};
